### ISSUE TITLE
Make выдаёт ошибку

### ISSUE THREAD

**Issue by Rashid-S** [dralex/orbita-simulator#7]
Здравствуйте.

При выполнении команды _make_ (в директории _...models/earth_ ) выдаёт ошибку 

```
rm -rf venus
pyxbgen xml-schemas/devices.xsd -m venus.devices
Traceback (most recent call last):
    File "/home/rashid/.local/bin/pyxbgen", line 4, in <module> import pyxb.xmlschema
    File "/home/rashid/.local/lib/python3.10/site-packages/pyxb/xmlschema/__init__.py", line 12, in <module>
      from pyxb.xmlschema.structures import Schema as schema
    File "/home/rashid/.local/lib/python3.10/site-packages/pyxb/xmlschema/structures.py", line 47, in <module>
      from pyxb.binding import basis, datatypes, facets
    File "/home/rashid/.local/lib/python3.10/site-packages/pyxb/binding/__init__.py", line 8, in <module>
      from . import datatypes
    File "/home/rashid/.local/lib/python3.10/site-packages/pyxb/binding/datatypes.py", line 1266, in <module>
      from . import content
    File "/home/rashid/.local/lib/python3.10/site-packages/pyxb/binding/content.py", line 807, in <module>
      class _PluralBinding (collections.MutableSequence):
AttributeError: module 'collections' has no attribute 'MutableSequence'
make: *** [Makefile:3: all] Ошибка 1
```

Как это исправить ?

**Comment by dralex** [comment]
Проверьте пожалуйста, что у вас Python 3.8+ (хотя из логов кажется, что это так) и pyxb версии хотя бы 1.2.6

**Comment by Rashid-S** [comment]
> Обратитесь пожалуйста, что у вас Python 3.8+ (хотя из логов кажется, что это так) и версия pyxb хотя бы 1.2.6

Python 3.10; Pyxb 1.2.6

Как с вами можно по почте связаться? ящик aleksey@fedoseev.net Mail.ru показывает что не существует.

**Comment by dralex** [comment]
Ящик существует, пишите на него смело. 

С ошибкой все понятно. Работает только в версии Python 3.9 и ниже, потому что pyxb уже старый и не поддерживается в связи с изменениями в интерпретаторе. Есть лайфхак, попробую обойти.

**Comment by dralex** [comment]
Можно попробовать исправить так:
открыть на редактирование файл pyxbgen и перед импортами добавить следующее:

import collections
collections.MutableSequence = collections.abc.MutableSequence

**Comment by dralex** [comment]
Попробуйте взять последнюю версию репозитория. Добавил небольшой хак, чтобы обойти старый pyxb.

**Comment by Rashid-S** [comment]
Алексей, теперь такую ошибку выдает )))
 
rm -rf venus
python3 ../../pyxbgen.py xml-schemas/devices.xsd -m venus.devices
Traceback (most recent call last):
  File "/home/rashid/Загрузки/orbita-simulator-main/models/earth/../../pyxbgen.py", line 8, in <module>
    collections.MutableSequence = collections.abc.MutableSequence
AttributeError: module 'collections' has no attribute 'abc'
make: *** [Makefile:3: all] Ошибка 1
 
 
Может лучше нам в телеграме ***@***.***_s) общаться или в ватсапе (+7-962-046-92-63) ?

  
>Среда, 21 июня 2023, 17:35 +03:00 от Alexey Fedoseev ***@***.***>:
> 
> 
>Попробуйте взять последнюю версию репозитория. Добавил небольшой хак, чтобы обойти старый pyxb.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <dralex/orbita-simulator/issues/7/1600957321 @ github . com> 
 
 
--
Рашид Сулейманов
Отправлено из Почты  Mail.ru

**Comment by Rashid-S** [comment]
> Попробуйте взять последнюю версию репозитория. Добавил небольшой хак, чтобы обойти старый pyxb.

теперь (с Python 3.10) вот так )))

```
rm -rf venus
python3 ../../pyxbgen.py xml-schemas/devices.xsd -m venus.devices
Traceback (most recent call last):
  File "/home/rashid/Загрузки/orbita-simulator-main/models/earth/../../pyxbgen.py", line 8, in <module>
    collections.MutableSequence = collections.abc.MutableSequence
AttributeError: module 'collections' has no attribute 'abc'
make: *** [Makefile:3: all] Ошибка 1 
```

**Comment by dralex** [comment]
Поправил import, теперь должно сработать.

**Comment by Rashid-S** [comment]
> Поправил import, теперь должно сработать.

теперь такую ошибку выдает

```
rm -rf venus
python3 ../../pyxbgen.py xml-schemas/devices.xsd -m venus.devices
Python for venus requires 1 modules
python3 ../../pyxbgen.py xml-schemas/missions.xsd -m venus.missions
Python for venus requires 1 modules
python3 ../../pyxbgen.py xml-schemas/probe.xsd -m venus.probe
Python for venus requires 1 modules
python3 ../../pyxbgen.py xml-schemas/global_parameters.xsd -m venus.global_parameters
Python for venus requires 1 modules
python3 ../../pyxbgen.py xml-schemas/global_config.xsd -m venus.global_config
Python for venus requires 1 modules
python3 ../../pyxbgen.py xml-schemas/shortlog.xsd -m venus.shortlog
Python for venus requires 1 modules
protoc --python_out=. api/systems.proto
make: protoc: Нет такого файла или каталога
make: *** [Makefile:9: all] Ошибка 127
```

какую версию  Pytnon используете? 3.10 ?

**Comment by dralex** [comment]
Это у вас не стоит Google Protocol Buffers https://developers.google.com/protocol-buffers/
Нужно поставить через pip питоновский код, а сам копилятор protoc у меня стоит как пакет в snap, наверняка и в дистрибутиве он есть.

**Comment by dralex** [comment]
Поправил документацию по установке заодно.

**Comment by Rashid-S** [comment]
> Это у вас не стоит Google Protocol Buffers https://developers.google.com/protocol-buffers/ Нужно поставить через pip питоновский код, а сам копилятор protoc у меня стоит как пакет в snap, наверняка и в дистрибутиве он есть.

по ссылке https://github.com/protocolbuffers/protobuf/tree/main/python  попробовал установить Protobuf  `pip install protobuf` 
Мне показывает что вроде есть уже этот пакет
```
rashid@rashid-VirtualBox:~$ pip3 install protobuf
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (3.12.4)
```

Да и snap тоже уже есть
```
rashid@rashid-VirtualBox:~$ sudo apt install snapd
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Уже установлен пакет snapd самой новой версии (2.58+22.04.1).
snapd помечен как установленный вручную.
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
```

**Comment by Rashid-S** [comment]
> Это у вас не стоит Google Protocol Buffers https://developers.google.com/protocol-buffers/ Нужно поставить через pip питоновский код, а сам копилятор protoc у меня стоит как пакет в snap, наверняка и в дистрибутиве он есть.

@dralex, Если выполнить вот это, у вас какое значение принтует:
```
$ python
Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf.internal import api_implementation
>>> print(api_implementation.Type())
```
у меня принтует  `upb` . Может должно выводиться `python` ?

**Comment by dralex** [comment]
Вам нужен не просто snap, а snap-пакет protobuf.
Вот так, например:

`# snap install protobuf`

Нужен и пакет из pip (protobuf для питона), и сам protobuf

**Comment by Rashid-S** [comment]
> Вам нужен не просто snap, а snap-пакет protobuf. Вот так, например:
> 
> `# snap install protobuf`
> 
> Нужен и пакет из pip (protobuf для питона), и сам protobuf

Всё получилось @dralex . Спасибо за помощь.
