### ISSUE TITLE
Satellite swarms and inter-satellite communication

### ISSUE THREAD

**Issue by dralex** [dralex/orbita-simulator#8]
Add inter-satellite communication to the radio model and the control programs to play with the different swarm algorithms.
Supply the new model by a satellite swarm mission.

**Comment by Rashid-S** [comment]
> Добавьте межспутниковую связь к модели радио и управляющим программам, чтобы поиграть с различными алгоритмами роя. Поставьте новую модель с помощью спутниковой миссии.

Может для начала есть смысл потренироваться на простых графах, муравьином алгоритме ?

**Comment by dralex** [comment]
Multiple probes added by commit 33c8aa8a41dfed84913ebfba8224ed1836d4d8d8
